// angular-client/src/app/transactions/add-transaction/add-transaction.component.ts
import { Component, OnInit } from '@angular/core';
import { TransactionsService } from '../transactions.service';

@Component({
  selector: 'bd-add-transaction',
  templateUrl: './add-transaction.component.html',
})
export class AddTransactionComponent implements OnInit {

  text: string;
  amount: number;

  constructor(private transactionService: TransactionsService) { }

  ngOnInit(): void {
  }

  addTransaction(): void {
    this.transactionService.addTransaction(this.text, this.amount);
    this.text = "";
    this.amount = null;
  }

}

<h3>Add new transaction</h3>
<form (submit)="addTransaction()">
  <div class="form-control">
    <label for="text">Text</label>
    <input type="text" name="text" [(ngModel)]="text" placeholder="Enter text..." />
  </div>
  <div class="form-control">
    <label for="amount"
      >Amount <br />
      (negative - expense, positive - income)</label
    >
    <input type="number" name="amount" [(ngModel)]="amount" placeholder="Enter amount..." />
  </div>
  <button class="btn">Add transaction</button>
</form>

// react-client/src/components/AddTransaction.js
import React, { useState, useContext } from 'react'
import { GlobalContext } from '../context/GlobalState';

export const AddTransaction = () => {
  const { addTransaction } = useContext(GlobalContext);

  const [text, setText] = useState('');
  const [amount, setAmount] = useState(0);

  const onSubmit = e => {
    e.preventDefault();

    const transaction = {
        id: Math.floor(Math.random() * 100000000),
        text,
        amount: +amount
    };

    addTransaction(transaction);
  };

  return (
    <>
      <h3>Add new transaction</h3>
      <form onSubmit={onSubmit}>
        <div className="form-control">
          <label htmlFor="text">Text</label>
          <input type="text" value={text} onChange={(e) => setText(e.target.value)} placeholder="Enter text..." />
        </div>
        <div className="form-control">
          <label htmlFor="amount"
            >Amount <br />
            (negative - expense, positive - income)</label
          >
          <input type="number" value={amount} onChange={(e) => setAmount(e.target.value)}placeholder="Enter amount..." />
        </div>
        <button className="btn">Add transaction</button>
      </form>
    </>
  )
}
