// angular-client/src/app/transactions/income-expenses/income-expenses.component.ts
import { Component, OnInit } from '@angular/core';
import { Transaction } from 'src/app/core/models/transaction';
import { Observable } from 'rxjs';
import { TransactionsService } from '../transactions.service';

@Component({
  selector: 'bd-income-expenses',
  templateUrl: './income-expenses.component.html',
})
export class IncomeExpensesComponent implements OnInit {

  transactions$: Observable<Transaction[]>;

  income: string;
  expense: string;

  constructor(private transactionService: TransactionsService) {
    this.transactions$ = transactionService.entities$;
  }

  ngOnInit(): void {
    this.transactions$.subscribe((transactions: Transaction[]) => {
      const amounts = transactions.map(transaction => transaction.amount);

      this.income = amounts
        .filter(item => item > 0)
        .reduce((acc, item) => (acc += item), 0)
        .toFixed(2);
    
      this.expense = (
        amounts
        .filter(item => item < 0)
        .reduce((acc, item) => (acc += item), 0) * -1
      ).toFixed(2);
    });
  }

}

<div class="inc-exp-container">
  <div>
    <h4>Income</h4>
    <p class="money plus">{{ income | currency }}</p>
  </div>
  <div>
    <h4>Expense</h4>
    <p class="money minus">{{ expense | currency }}</p>
  </div>
</div>

// react_client/src/components/IncomeExpenses.js
import React, { useContext } from 'react'
import { GlobalContext } from '../context/GlobalState'
import { numberWithCommas } from '../util/format';

export const IncomeExpenses = () => {
  const { transactions } = useContext(GlobalContext);

  const amounts = transactions.map(transaction => transaction.amount);

  const income = amounts
    .filter(item => item > 0)
    .reduce((acc, item) => (acc += item), 0)
    .toFixed(2);

  const expense = (
    amounts
    .filter(item => item < 0)
    .reduce((acc, item) => (acc += item), 0) * -1
  ).toFixed(2);

  return (
    <div className="inc-exp-container">
      <div>
        <h4>Income</h4>
        <p className="money plus">${ numberWithCommas(income) }</p>
      </div>
      <div>
        <h4>Expense</h4>
        <p className="money minus">${ numberWithCommas(expense) }</p>
      </div>
    </div>
  )
}
