// angular-client/src/app/transactions/transaction-list/transaction/transaction.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { Transaction } from "src/app/core/models/transaction";
import { TransactionsService } from "../../transactions.service";

@Component({
  selector: 'bd-transaction',
  templateUrl: './transaction.component.html',
})
export class TransactionComponent implements OnInit {

  private _transaction: Transaction;
  @Input()
  get transaction(): Transaction {
    return this._transaction;
  }

  set transaction(value: Transaction) {
    if (value) {
      this._transaction = value;
      this.sign = this._transaction.amount < 0 ? '-' : '+';
      this.color = this._transaction.amount < 0 ? 'minus' : 'plus';
    }
  }

  sign: string; 
  color: string;

  constructor(private transactionService: TransactionsService) { }

  ngOnInit(): void {
  }

  deleteTransaction(id: string): void {
    this.transactionService.deleteTransaction(id);
  }

  editTransaction(id: string): void {
  }
}

<li [className]="color">
  {{ transaction.text }} <span>{{ sign }}{{ transaction.amount | abs | currency }}</span>
  <button (click)="deleteTransaction(transaction._id)" class="delete-btn">x</button>
  <button (click)="editTransaction(transaction._id)" class="edit-btn">e</button>
</li>

// react_client/src/components/Transaction.js
import React, { useContext } from 'react'
import { GlobalContext } from '../context/GlobalState';
import { numberWithCommas } from '../util/format';

export const Transaction = ({ transaction }) => {
  const { deleteTransaction } = useContext(GlobalContext);

  const sign = transaction.amount < 0 ? '-' : '+';
  const color = transaction.amount < 0 ? 'minus' : 'plus';

  return (
    <li className={color}>
      {transaction.text} <span>{sign}${ numberWithCommas(Math.abs(transaction.amount))}</span>
      <button onClick={() => deleteTransaction(transaction._id)} className="delete-btn">x</button>
    </li>
  )
}
